### ISSUE TITLE
"prefix" for training T5

### ISSUE THREAD

**Issue by Albert-Ma** [castorini/docTTTTTquery#49]
Hi,

Just want to know whether you use a prefix, e.g. 'summarize:', 'translate:' and etc, when training T5.

If I'm not wrong, you maybe didn't specify a prefix and only add a `</s>` at the end of the input document.
If so, I'm curious whether adding a prefix would improve the performance. Since T5 uses prefixes when fine-tuning on the downstream tasks in their paper,  maybe it explores the pre-training knowledge effectively? I'm new to T5.

Thanks,

**Comment by rodrigonogueira4** [comment]
Hi, thanks for your question.

I see the prefix as a way to tell the model which task it should be performing (translation, summarization, etc). Since doc2query performs only one task, a prefix doesn't seem necessary. However, it would be interesting to compare the current version against a prefixed one.

**Comment by Albert-Ma** [comment]
Got it.
Thanks for your quick reply.
